### ISSUE TITLE
Madibeng is not on the North West list

### ISSUE THREAD

**Issue by mwolfaardt** [beyarkay/eskom-calendar#13]
Please can you add Madibeng for the North West province as I see it's not on the list.

**Comment by beyarkay** [comment]
Hey! thanks for pointing that out. I'd love to add Madibeng, but I can't find an official loadshedding schedule? The only things I can find are:
- [The Madibeng>madibeng link on eskom.co.za](https://www.eskom.co.za/distribution/customer-service/outages/municipal-loadshedding-schedules/north-west/) which points me to:
- [this correction notice](https://www.madibeng.gov.za/correction-on-the-times-and-venues-of-loadshedding/) which doesn't actually show the full loadshedding schedule (and I couldn't find anything else on the website)

I know EskomSePush has a loadshedding schedule for madibeng, but I can't find out where their source of information is. If you can point me to the URL with a PDF or loadshedding schedule then I'll happily add it.

**Comment by mwolfaardt** [comment]
We also fall under skeerpoort (6). To be more precise

**Comment by beyarkay** [comment]
Okay, I can't find any schedules for skeerpoort either. Do you know where to find the official loadshedding schedule?

**Comment by mwolfaardt** [comment]
Try the following URL : https://loadshedding.eskom.co.za/LoadShedding/GetScheduleM/1046876/1/North%20West/2097

**Comment by beyarkay** [comment]
Oh that's weird. So I looked into the eskom API given by your link at the start of the project, but ended up removing it because it didn't seem like it was providing the correct information, and I managed to parse the PDFs which did seem to provide the correct information.

I will look into this more and see what I can do to include it.

Note to future @beyarkay : This link: https://loadshedding.eskom.co.za/LoadShedding/DownloadFile?ID=1046876&Name=Skeerpoort will download the Skeerpoort PDF which is nicely formatted and includes one month's worth of data in a table.

**Comment by mwolfaardt** [comment]
I see there's a lot of new areas, will Skeerpoort be one of the upcoming changes?

**Comment by beyarkay** [comment]
I've got some personal things which are taking up my time at the moment, so I can't make guarantees about when it'll be added but it is absolutely on my list to do. 

If it's really a problem, you can submit a PR which  adds _generated/north-west-skeerport.csv_ in the correct format (have a look at the other CSVs, it's pretty intuitive) and that will cause the correct calendar files to be automatically generated.


By way of example, here's [generated/city-of-cape-town-area-1.csv](https://github.com/beyarkay/eskom-calendar/blob/main/generated/city-of-cape-town-area-1.csv):

```
date_of_month,start_time,finsh_time,stage 
 1,00:00,02:30,1 
 1,00:00,02:30,2 
 1,00:00,02:30,3 
 1,00:00,02:30,4 
 1,00:00,02:30,5 
 1,00:00,02:30,6 
 1,00:00,02:30,7 
 1,00:00,02:30,8 
 1,06:00,08:30,7 
 1,06:00,08:30,8 
 1,08:00,10:30,3 
 1,08:00,10:30,4 
 1,08:00,10:30,5 
 1,08:00,10:30,6 
 1,08:00,10:30,7
...
```

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:
-  Skeerpoort: https://eskomcalendar.co.za/ec?calendar=eskom-direct-6-even.ics

You can also search for other areas by going to https://eskomcalendar.co.za/ and typing your area in the search box.

Hope that helps! feel free to reopen the issue if you've got other questions.
