### ISSUE TITLE
Projected load shedding events that do happen aren't removed from the calendar

### ISSUE THREAD

**Issue by moderatoburrito** [beyarkay/eskom-calendar#15]
Something I've noticed so far using your load shedding calendar feed is that some events were created (for Cape Town area 15) at a time that load shedding was projected but when that gets revised, the events are still present. For example, at some point, load shedding was scheduled today for 18:00-20:30 but at present, no load shedding is scheduled.

I'm not sure if it is possible to periodically "clean" out events where no load shedding is actually taking place?

**Comment by beyarkay** [comment]
I think I know what happened here, and it's two-fold:

1. Unfortunately keeping track of the loadshedding schedule is a manual process. If you submit a commit to update [`manually_specified.yaml`](https://github.com/beyarkay/eskom-calendar/blob/main/manually_specified.yaml), then [this workflow](https://github.com/beyarkay/eskom-calendar/blob/main/.github/workflows/build_calendars.yaml) will be triggered, which will recompile all the calendars and publish them again. Once this occurs, your calendar application should pull down the new information and update your calendar accordingly.

    The issue here is the manual updating part. Anyone can make changes to `manually_specified.yaml`, but so far I'm the only one so if I miss an update then things get out of date until I fix them. An example commit would be [this one](https://github.com/beyarkay/eskom-calendar/commit/ce29dd5abbf070cd3a6a1ca9f9b5350418697c36).

2. The other issue is that we recently didn't have any loadshedding scheduled (although at the time of writing this might change it seems). I hadn't actually checked the proper YAML specification, so [I incorrectly specified an empty list](https://github.com/beyarkay/eskom-calendar/commit/72b525b1491fa6620269abb72278e53b5e37d0a1) which then [caused the build to fail](https://github.com/beyarkay/eskom-calendar/runs/7487043364?check_suite_focus=true), which caused the calendars to not get updated. I've just fixed this issue with [this commit](https://github.com/beyarkay/eskom-calendar/commit/a0d6128da79b7e0d92cc9bd74edabb032719321b).

So everything should be fixed now and your calendar should be up-to-date. Feel free to re-open if that's not the case!
