### ISSUE TITLE
Add loadshedding for Alberton (Ekurhuleni)

### ISSUE THREAD

**Issue by beyarkay** [beyarkay/eskom-calendar#150]
Website with schedule: https://www.ekurhuleni.gov.za/document/updated-alberton-load-shedding-schedules/

Also for:

- boksburg: https://www.ekurhuleni.gov.za/document/updated-boksburg-load-shedding-schedules/
-  benoni: https://www.ekurhuleni.gov.za/document/updated-benoni-load-shedding-schedules/
- germiston: https://www.ekurhuleni.gov.za/document/updated-germiston-load-shedding-schedule/
-

**Comment by beyarkay** [comment]
And for benoni: https://www.ekurhuleni.gov.za/document/updated-benoni-load-shedding-schedules/

**Comment by c4talyst** [comment]
Don't use these individual ones, they're out of date

Use these
https://www.ekurhuleni.gov.za/for-me/load-shedding-schedules/

**Comment by Ruandv** [comment]
You are already using the file that @c4talyst is referencing in your code for [ekurhuleni](https://github.com/beyarkay/eskom-calendar/blob/6ba24cb514e59653195086c9c15f90f3fb1a8c99/src/parse_ekurhuleni.py#L15).

**Comment by beyarkay** [comment]
Fixed by b390f488ea3544b4c1ddd768b5df517edda633d5
