### ISSUE TITLE
Missing schedule for Mangaung / Bloemfontein

### ISSUE THREAD

**Issue by IamC8** [beyarkay/eskom-calendar#156]
Hi. I noticed that you have no data for Bloemfontein. I have written code to extract it. 
Where can I post it or should I rather join?

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, I've been swamped recently. Could you send through the code to extract Manguang? If it looks all good then I'll add it to the project!

**Comment by beyarkay** [comment]
I've found the schedules [here](https://github.com/beyarkay/eskom-calendar/issues/80#issue-1383690865) as well:

> Power appears to be provided by Centlec: https://www.centlec.co.za/LoadShedding/LoadSheddingDocuments with the schedule available [here](https://www.centlec.co.za/LoadShedding/ViewFile?filePath=wwwroot%2FUploadedFiles%2FLoadShedding%2FCENTLEC%20Load%20Shedding%20Schedule%202022%20Updated_245d.pdf).

**Comment by beyarkay** [comment]
Hey @IamC8 , I've added Mangaung to [eskomcalendar.co.za](https://eskomcalendar.co.za), you can now search for the mangaug areas (universitas, bayswater, botshabelo, etc) and your calendar should pop up. I hope this helps! (and let me know if it doesn't)

As a final note, (and if you like the project), leaving a "star" (there's a button on [the main page](https://github.com/beyarkay/eskom-calendar)) would be much appreciated, as this helps more people discover eskom-calendar!
