### ISSUE TITLE
Please add Bothasig

### ISSUE THREAD

**Issue by Bushjumper** [beyarkay/eskom-calendar#164]
Hi @beyarkay 

As discussed on our call yesterday, we noticed that Bothasig was missing from the list of areas.

Thanks!
Graeme

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:
-  Bothasig: https://eskomcalendar.co.za/ec?calendar=eskom-direct-14-odd.ics
- Bothasig Plattekloof: https://eskomcalendar.co.za/ec?calendar=eskom-direct-2-odd.ics

Hope that helps! Feel free to open the issue again if you have any questions
