### ISSUE TITLE
No 2023 load shedding slots shown for all areas except Cape Town

### ISSUE THREAD

**Issue by robotic-coder** [beyarkay/eskom-calendar#220]
I'm not 100% sure this is *all* areas except Cape Town, but this is what I've observed from opening random ics files and comparing the average file sizes for the areas.

I suspect this is an issue with going across years in [manually_specified.yaml](https://github.com/beyarkay/eskom-calendar/blob/80a97e7e4838625f248eca053a045b80e8ca4670/manually_specified.yaml). Cape Town seems unaffected because it has new load shedding events starting in 2023, while the current event covering the rest of the country started in 2022.

Cape Town was probably also affected by this issue between 22:00 on the 31st and 5:00 on the 1st, but this wasn't as noticeable because it is only a 7-hour period.

**Comment by shaunkleyn** [comment]
I just wanted to open an issue as well after noticing that the last event that's pulling through for me (using https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-3.ics) was on 31 Dec. 

[Here's a link](https://calendar.google.com/calendar/embed?src=18ab206kfe47upp18lafo7rhp6r5lnea%40import.calendar.google.com&ctz=Africa%2FJohannesburg) to shared calendar on Google Calendar where I imported the ics file.

<img width="789" alt="image" src="https://user-images.githubusercontent.com/10231893/210225005-66a25f28-c3cc-4a97-884f-3f9fa946c98f.png">

**Comment by beyarkay** [comment]
Hrmm. That's not great. Thanks for logging the issue though! I'm looking into it now.

**Comment by beyarkay** [comment]
Okay it should be fixed by https://github.com/beyarkay/eskom-calendar/commit/db93b125f540b0d62b38532858bfc08bc8746f76, I'm just [waiting for the calendars to build](https://github.com/beyarkay/eskom-calendar/actions/runs/3824253828) and then I'll be able to confirm

**Comment by beyarkay** [comment]
Okay it's all fixed now. 

Previously:

```sh
╰→ curl -sL https://github.com/beyarkay/eskom-calendar/releases/download/latest/machine_friendly.csv | rg "gauteng-ekurhuleni-block-3"
gauteng-ekurhuleni-block-3,2022-12-31T06:00:00+02:00,2022-12-31T08:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
```

Now:

```sh
╰→ curl -sL https://github.com/beyarkay/eskom-calendar/releases/download/latest/machine_friendly.csv | rg "gauteng-ekurhuleni-block-3"
gauteng-ekurhuleni-block-3,2022-12-31T06:00:00+02:00,2022-12-31T08:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-01T04:00:00+02:00,2023-01-01T06:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-02T04:00:00+02:00,2023-01-02T06:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-02T12:00:00+02:00,2023-01-02T14:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-03T12:00:00+02:00,2023-01-03T14:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-03T20:00:00+02:00,2023-01-03T22:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-04T20:00:00+02:00,2023-01-04T22:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-05T02:00:00+02:00,2023-01-05T04:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-06T02:00:00+02:00,2023-01-06T04:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-06T10:00:00+02:00,2023-01-06T12:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-07T10:00:00+02:00,2023-01-07T12:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-07T18:00:00+02:00,2023-01-07T20:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-08T18:00:00+02:00,2023-01-08T20:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-09T00:00:00+02:00,2023-01-09T02:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-10T00:00:00+02:00,2023-01-10T02:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-10T08:00:00+02:00,2023-01-10T10:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-11T08:00:00+02:00,2023-01-11T10:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-11T16:00:00+02:00,2023-01-11T18:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
gauteng-ekurhuleni-block-3,2023-01-12T16:00:00+02:00,2023-01-12T18:00:00+02:00,2,"https://twitter.com/Eskom_SA/status/1609169105369681920"
```

I've also been working on the website: https://beyarkay.github.io/ec?calendar=gauteng-ekurhuleni-block-3.ics which is still a little rough around the edges, but should make the new-user experience a _lot_ better.

Thanks for raising the bug @robotic-coder ! I really appreciate it.

**Comment by beyarkay** [comment]
No problem!
