### ISSUE TITLE
Can’t remove calendar

### ISSUE THREAD

**Issue by Tina9cherry** [beyarkay/eskom-calendar#237]
Hi there, I can’t seem to remove a calendar once added on my Google account via my iPhone. The one calendar I added is correct (area 10, which I manually added as a subscription calendar), but there is a second calendar for area 6, which I added by following a link. There was an option to add the calendar directly instead of copying the URL into the subscription calendar section - when I clicked on this option, the calendar for area 6 showed up, but there’s not option to de-select or delete it.

min other words, the events appear in my calendar, but there is no way to collectively delete them. I have to delete every event individually.

Please help? Thanks!

**Comment by beyarkay** [comment]
Hi there, apologies for the delay in getting back to you, this slipped under my radar.

Unfortunately this is a problem in the calendar app, and not in eskom-calendar. If you add the calendar by clicking on the link, then your calendar app will only add the next few days worth of events to your calendar (and after those few days, you won't get any updates) The only way to remove them is to manually delete every single event.

If you subscribe to a calendar, then you can delete all events from that subscription by removing the subscription. Subscribing to a calendar will also update you with new events as they get published. 

I hope that clarifies things! and again, I'm sorry for taking so long to get back to you.
