### ISSUE TITLE
Please remove emoji's

### ISSUE THREAD

**Issue by Mammouth100** [beyarkay/eskom-calendar#242]
Hi Boyd,

The calendars are working super great, but with the stage 6 load shedding their calendars are filled with the negative emoji's also.

Could you please consider removing them, or replacing them with something happier?

Thank you

Christo Versteeg

**Comment by beyarkay** [comment]
Hey! thanks for your interest in the project. I kinda like the emojis, but I'd agree that the higher stages are a bit violent, especially for business usage. I do however want to keep some correlation between more loadshedding and sadder emojis, but am very open to suggestions.

Could you suggest an alternative for each of the stages 1 through to 8? For reference, here are the current emojis, as defined on [this line of code](https://github.com/beyarkay/eskom-calendar/blob/main/src/main.rs#L232):

- Stage 0: 💡
- Stage 1: ☹️
- Stage 2: 😖
- Stage 3: 😤
- Stage 4: 😡
- Stage 5: 🤬
- Stage 6: 🔪
- Stage 7: ☠️
- Stage 8: ⚰️

@shaunkleyn wondering if you have any strong thoughts on this?

**Comment by shaunkleyn** [comment]
Hi Boyd.

Hmmm... 🤔 I don't have anything against the emojis, to be honest, I don't
really pay attention to them. I guess it does make it a bit more "fun" and
casual but as a user I'm just concerned about the stage. If you want to
keep emoji's, perhaps consider replacing them with the numbered emoji's?
1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣

In short, I probably wouldn't have even noticed if you removed them.

**Comment by Mammouth100** [comment]
Hi Boyd and Shaun,

Personally I though the emojis were quite clever, and in some morbid way humerous.

I guess now that the events are added into the inner-sanctum of peoples organizational zen place, they could be a bit sensitive if their diary is plastered with knives or sculls.

The numbered emoji is a good second option, I looked for alternatives but none have a nice progression and would be neutral enough.

🐜🐞🐛🐌🐀🐇🦏🐘

**Comment by beyarkay** [comment]
I could be swayed to the numeral emojis, although I'd probably look at formatting each event like:

Cape Town 15 Stage 6️⃣

And at that point I'm not sure what the emoji adds over just a plain ol' number?

@Mammouth100 thanks for your input, I'd like to keep some sort of semantic meaning to the emojis so they at least vaguely convey increasing levels of concern, but I agree that knives and skulls are a bit much. 

I think unless anyone else has strong opinions, I'm going to change the emojis to a less violent set:

0😁 1😕 2☹️ 3😟 4😣 5😭 6😫 7😤 8😡

I'm open to suggestions about the exact emojis for each stage, but:

- there should be some gradient of change from stage 0 to stage 8
- they should be a bit playful
- none of the more violent emojis (skulls, coffins, etc)

**Comment by Mammouth100** [comment]
Hi Boyd,

The new sequence of emojis looks great, and the feedback I got was also good.

Thanks for the update.

By the way, I have used your calendars and created really easy subscription pages. Let me know if you want one.

www.calendaronmyphone.com

**Comment by beyarkay** [comment]
This should be fixed by [cf62379](https://github.com/beyarkay/eskom-calendar/commit/cf62379338ba1aaa4c878620c62bcfa0bb0f4287)
