### ISSUE TITLE
Nkandla and Melmoth

### ISSUE THREAD

**Issue by popsru1es** [beyarkay/eskom-calendar#243]
Hi There

Can you please add Nkandla and Melmoth

Thanx
Gideon

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:
-  Nkandla: https://eskomcalendar.co.za/ec?calendar=eskom-direct-1-even.ics 
- Melmoth: https://eskomcalendar.co.za/ec?calendar=eskom-direct-1-even.ics

Hope that helps! Feel free to open the issue again if you have any questions

**Comment by popsru1es** [comment]
Thank You Very Much
