### ISSUE TITLE
Still Bay. 

### ISSUE THREAD

**Issue by popsru1es** [beyarkay/eskom-calendar#245]
Could you please add StillBay Western Cape

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:
-  Still Bay: https://eskomcalendar.co.za/ec?calendar=eskom-direct-7-odd.ics 

Hope that helps! Feel free to open the issue again if you have any questions

**Comment by popsru1es** [comment]
Thank You Very Much
