### ISSUE TITLE
Missing schedule for KZN, Durban, waterfall, block 8

### ISSUE THREAD

**Issue by DyllanDarcy** [beyarkay/eskom-calendar#267]
Hi there, is there an ics for KZN, Durban, waterfall, block 8? I don't know if I'm missing something but can't find one.

This is such an awesome project man!

Kind regards

**Comment by beyarkay** [comment]
Glad you like the project!

Durban is proving to be tricky to add, but I'll post an update here as soon as your area has been added.

Can I ask how you heard about the project?

**Comment by DyllanDarcy** [comment]
Hey man that sounds good! 
I was trying to use ESP's API to sync with my Home Assistant calender, so my wife could ask our smart speaker when load shedding would be. But I couldn't get it to work without updating manually each day. 

A few Google results and I came across your Reddit post

Kind regards Dyllan

**Comment by beyarkay** [comment]
Hey! I've added all of the areas managed by eThekwini municipality, so all of the durban areas are now searchable on [eskomcalendar.co.za](https://eskomcalendar.co.za).

Specifically, @DyllanDarcy Waterfall, block 8, is available here: https://eskomcalendar.co.za/ec?calendar=kwazulu-natal-ethekwini-block-8.ics

As a final note, (and if you like the project), leaving a "star" (there's a button on [the main page](https://github.com/beyarkay/eskom-calendar)) would be much appreciated, as this helps more people discover eskom-calendar!
