### ISSUE TITLE
Are there any objections with reading the machine_friendly.csv from Github in a closed source program?

### ISSUE THREAD

**Issue by pierre-pretorius** [beyarkay/eskom-calendar#310]
Congratulations @beyarkay this looks like a really impressive project. 

It's licensed as GPLv3 which typically covers the source code rather than the generated output, but I would like to make sure I honor what you intended with the license.  Do you have any objections to a closed source program that already has many users to read the machine_friendly.csv file from Github and show load shedding events to it's users? It will include attribution to this project and encourage participation.

**Comment by beyarkay** [comment]
Hi there! Thanks for reaching out. I'm not 100% sure about this case either, and have [reached out](https://opensource.stackexchange.com/questions/13847/if-my-gplv3-program-produces-a-useful-csv-file-can-closed-source-code-use-that) to get another opinion. I'll reply here once I get confirmation.

Can I ask what the closed source project is, and how you heard about eskom-calendar?

**Comment by pierre-pretorius** [comment]
Thank you @beyarkay, the [answer that was posted](https://opensource.stackexchange.com/questions/13847/if-my-gplv3-program-produces-a-useful-csv-file-can-closed-source-code-use-that) is what I expected, which is that commercial use is of the CSVs are fine.  Regardless of their answer, I want to confirm how you intend it to be used since you picked GPLv3 instead of the Github default which is MIT.

If you google "github loadshedding" and click the first link, then your project is at the top.  I found it when I was looking for projects that provide load shedding schedules as I'm looking for an open data source to use in SolarAssistant: https://solar-assistant.io/

**Comment by beyarkay** [comment]
Hi @pierre-pretorius, hope all is well. Just want to check in and ask if you've had any trouble integrating with eskom-calendar, or if you've got any feature requests?

I've had some of the Solar Assistant users open bug reports which has been super helpful.

**Comment by pierre-pretorius** [comment]
Hi, it was easy to do thank you.  Your approach of using Github as a server for the data works great.  I created the page below to guide users to your project.  I link to the page below from within SolarAssistant.

https://solar-assistant.io/help/grid/eskom#where-does-the-data-come-from

The area metadata is cached in memory for 30 days, while the schedule is cached in memory for 12 hours.  It's to reduce the bandwidth requirements for users.

Good to hear our users are offering to help out.  You will find they are quite technical with many being able to write code.

**Comment by beyarkay** [comment]
Yes, I've had really good experiences with them, they're all eager to help out and to provide the information I need to fix problems. Glad Github-as-a-server is working well (although long term I'd like to move away from it).

With regards to caching the area metadata & schedule, I see why you'd want to do that, although it can be tricky when things update.
