### ISSUE TITLE
Missing area schedule: Universitas, Bloemfontein, Free State

### ISSUE THREAD

**Issue by barry8212** [beyarkay/eskom-calendar#312]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

Hi,

I trust all is well. The details is as follow:

Area: Universitas
City: Bloemfontein
Province: Free State
Munic: Mangaung
Group 4

I bought Solar Assistant and saw it on their website

Thanks for the assistance.

Kind Regards,

Barry

**Comment by beyarkay** [comment]
Hi there!

Thanks for getting in touch, I'll look into adding this area shortly.

**Comment by beyarkay** [comment]
Hey! I've added mangaung to the calendar. You can now search for universitas on [eskomcalendar.co.za](https://eskomcalendar.co.za) and your calendar should pop up! (let me know if it doesn't). I hope this works for you.

As a final note, (and if you like the project), leaving a "star" (there's a button on [the main page](https://github.com/beyarkay/eskom-calendar)) would be much appreciated, as this helps more people discover eskom-calendar!
