### ISSUE TITLE
Area: Fichardpark (part NW) - Group 4

### ISSUE THREAD

**Issue by Waltervh31** [beyarkay/eskom-calendar#328]
**What area(s) couldn't you find on [eskomcalendar.co.za] (https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

**Comment by Waltervh31** [comment]
Area: Fichardpark (part NW) - Groep 4
Municipality: Mangaung ( Bloemfontein )

**Comment by beyarkay** [comment]
Hey, thanks for filing the bug report. There are a few other areas affected by a similar issue, so I'll get to this as soon as I can.
