### ISSUE TITLE
 machine_friendly.csv has disappeared...

### ISSUE THREAD

**Issue by JurieVorster** [beyarkay/eskom-calendar#334]
The CSV files on Github have disappeared, this project shutting down?
Particularly .../eskom-calendar/releases/download/latest/machine_friendly.csv

**Comment by beyarkay** [comment]
This project is very much alive, but thanks for letting me know that it's disappeared. Looking into it now.

**Comment by beyarkay** [comment]
Okay I've been making some performance improvements on just about everything, so [I've triggered a new release](https://github.com/beyarkay/eskom-calendar/actions/runs/4628657348/jobs/8194145959) which should make it available again in ~5 minutes.

**Comment by beyarkay** [comment]
Aaaaand we're back: https://github.com/beyarkay/eskom-calendar/releases/download/latest/machine_friendly.csv

**Comment by beyarkay** [comment]
Thanks Jurie for raising my attention to this, things could have gotten out of hand quite quickly otherwise. I'm going to look into creating some alarms to ensure `machine_friendly.csv` is always up and running.

**Comment by Dave-DigiMim** [comment]
Boyd
I use your machine_friendly.csv to create the following  
I get the current loadshedding stage from   https://loadshedding.eskom.co.za/LoadShedding/GetStatus

https://www.mrps.co.za/files/steyn.html

this my area  from https://github.com/beyarkay/eskom-calendar/releases/download/latest/machine_friendly.csv right now
It still show the old data form earlier on Thursday  even though your tweet link shows
 
![image](https://user-images.githubusercontent.com/4798359/230566478-f7936a06-afb1-4c00-8766-22685b1af928.png)

eskom-direct-3-even,2023-04-05T18:00:00+02:00,2023-04-05T20:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-06T02:00:00+02:00,2023-04-06T04:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-06T10:00:00+02:00,2023-04-06T12:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-06T18:00:00+02:00,2023-04-06T20:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-07T02:00:00+02:00,2023-04-07T04:30:00+02:00,4,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-07T18:00:00+02:00,2023-04-07T20:30:00+02:00,2,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-08T18:00:00+02:00,2023-04-08T20:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-09T00:00:00+02:00,2023-04-09T02:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-09T16:00:00+02:00,2023-04-09T18:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-10T00:00:00+02:00,2023-04-10T02:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1643610532090355717"
eskom-direct-3-even,2023-04-11T00:00:00+02:00,2023-04-11T02:30:00+02:00,3,"https://twitter.com/Eskom_SA/status/1643610532090355717"

**Comment by beyarkay** [comment]
Hi @Dave-DigiMim , I'm not sure I understand what is wrong? 

The [most recent eskom loadshedding update](https://twitter.com/Eskom_SA/status/1643610532090355717) was on Wednesday 2023-04-05, and that update is what is referenced in `machine_friendly.csv`. 

And then the schedules have been calculated correctly according to that announcement from eskom. 

I checked the schedule for [eskom-direct-3-even](https://eskomcalendar.co.za/ec?calendar=eskom-direct-3-even.ics) on https://eskomcalendar.co.za and that seems correct to me, and matches what is shown on EskomSePush.

Could you clarify the problem you're having?

**Comment by Dave-DigiMim** [comment]
Sorry , my mistake looking at the machine friendly csv   I was seeing 4's and 3's  when its stage 1.. However that was from past days.. I guess it's just because we seem to only be getting stage 3 as well.
Yes the data is right sorry...

**Comment by beyarkay** [comment]
Okay, no worries! Glad everything's sorted out now.
