### ISSUE TITLE
Missing area schedule / Bugged area: Brackenhurst

### ISSUE THREAD

**Issue by KevinCowleys** [beyarkay/eskom-calendar#338]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

Brackenhurst (1) | City of Ekurhuleni

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

This should be part of the gauteng-ekurhuleni-block-1.ics, but the file under releases seems to have the wrong time for the area. It shows loadshedding will be at 18:00-20:00 at Stage 3 on Sunday the 9th of March. However, that's wrong, as other apps shows loadshedding between 20:00-22:00 at Stage 2.

**Comment by beyarkay** [comment]
Hi there, I'm looking into this now.

**Comment by KevinCowleys** [comment]
Hi @beyarkay , thank you for adding it on the site, but the other issue is that the github .ics files are showing the wrong loadshedding info compared to other apps and your website.

For example Wednesday:

gauteng-ekurhuleni-block-1.ics
Github - 18:00-21:59
Website - 20:00-23:59

mpumalanga-secunda.ics
Github - 21:00-01:30
Website -  23:00-01:30

city-of-cape-town-area-13.ics
Github - 18:00-20:30
Website - 20:00-22:30

**Comment by beyarkay** [comment]
Having a look now...

**Comment by beyarkay** [comment]
Hi @KevinCowleys could you please refresh the website and confirm that you still are seeing problems? Ekurhuleni-block-1 is showing the same schedule for me on the website, on the calendar, and on EskomSePush

**Comment by KevinCowleys** [comment]
@beyarkay, I can't seem to get it working properly, the .ics seems to be wrong? That's the correct one to use with calendars, right?

https://github.com/beyarkay/eskom-calendar/releases/download/latest/city-of-cape-town-area-13.ics

It used to work fine that way, now it just doesn't show the correct schedules and when viewing the .ics it shows this date, which should mean it's the latest: DTSTAMP:20230412T125647Z.

Here's an example of an external site viewing the .ics:
![image](https://user-images.githubusercontent.com/61455840/231466427-f8715814-a0cf-41fc-b413-57cd4397ded7.png)

**Comment by beyarkay** [comment]
I think the problem has been the many many LS updates which have happened in the last hour or so, which made things go a bit funky. There is one final update from [CoCT](https://twitter.com/CityofCT/status/1646127260875870209) and from [Eskom](https://twitter.com/Eskom_SA/status/1646138476235030530) which are [being processed right now](https://github.com/beyarkay/eskom-calendar/actions/runs/4678738912), and this update should fix all the problems.

I'll review this issue once this latest update has been published, and confirm that things actually have been fixed.
