### ISSUE TITLE
western-cape-stellenbosch.ics missing

### ISSUE THREAD

**Issue by g-regex** [beyarkay/eskom-calendar#355]
Hi Boyd! First of all, thanks for maintaining this great service <3

I've just noted that the [western-cape-stellenbosch.ics](https://github.com/beyarkay/eskom-calendar/releases/download/latest/western-cape-stellenbosch.ics) file disappeared from the assets of the latest release. Maybe you'd like to look into that.

Cheers.

**Comment by beyarkay** [comment]
Hi there, [`western-cape-stellenbosch`](https://github.com/beyarkay/eskom-calendar/releases/download/latest/western-cape-stellenbosch.ics) should be back now, there was a little hiccup related to adding some other areas.
