### ISSUE TITLE
Cape town Area 14 schedule is not right

### ISSUE THREAD

**Issue by Sandbox2000** [beyarkay/eskom-calendar#369]
city-of-cape-town-area-14.ics does not give the correct loadshedding schedule.

**Comment by beyarkay** [comment]
<img width="905" alt="Screenshot 2023-04-16 at 22 53 13" src="https://user-images.githubusercontent.com/33420535/232341592-e6fb4eb8-9c00-4cdf-b729-74759ac80ed3.png">

[The website](https://eskomcalendar.co.za/ec/?calendar=city-of-cape-town-area-14.ics) says the same thing as eskom se push.
