### ISSUE TITLE
Missing area schedule

### ISSUE THREAD

**Issue by pjburg3r** [beyarkay/eskom-calendar#375]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Mangaung universitas (4) on EskomSePush 

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
SolarAssistant

**Any other information**
Times are not correct according to EskomSePush end actual schedule

**Comment by pjburg3r** [comment]
The schedule remains the same on all stages of loadshedding

**Comment by beyarkay** [comment]
Hi there, it looks like you want [free-state-mangaung-group-4
](https://eskomcalendar.co.za/ec?calendar=free-state-mangaung-group-4.ics). I've checked the schedule, and it matches up with what eskom se push says so I'm going to close this issue. Please feel free to reopen if something's still wrong, or to "star" the repository if you like what we do!
