### ISSUE TITLE
Missing: Sunridge Park (Area 31) (17)

### ISSUE THREAD

**Issue by mezzfit** [beyarkay/eskom-calendar#398]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

Sunridge Park (Area 31) (17)

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!

From the SolarAssistant app

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

**Comment by beyarkay** [comment]
This has been fixed as of 1074197, see https://eskomcalendar.co.za/ec/?calendar=nelson-mandela-bay-group-17.ics. You can (finally) search for them in the website (: Let me know if you see any issues (but they should all be correct)
