### ISSUE TITLE
Error in header

### ISSUE THREAD

**Issue by IamC8** [beyarkay/eskom-calendar#409]
In the file free-state-mangaung-group-6.csv, the header is ay_of_week and should be day_of_week

**Comment by beyarkay** [comment]
Thanks!

**Comment by beyarkay** [comment]
Closing this issue as [d3664e6](https://github.com/beyarkay/eskom-calendar/commit/d3664e6aa9a77d13d04db2d2a7d2fbef27117bc8) fixed the typo, and [9df4b6b](https://github.com/beyarkay/eskom-calendar/commit/9df4b6b6f6ce17c7a0a9a16f0139fe1c3b7549be) fixed the line in the source code which caused this error to not be raised.
