### ISSUE TITLE
No calendar for Ekurhuleni 

### ISSUE THREAD

**Issue by ChristlSnyman** [beyarkay/eskom-calendar#41]
IA there a calendar for Ekhurleni?

**Comment by beyarkay** [comment]
Hey!

I see Ekhurleni has non-eskom controlled loadshedding. Could you confirm that this the correct loadshedding schedule: https://www.ekurhuleni.gov.za/wp-content/uploads/2021/11/Ekurhuleni-Load-Shedding-Schedule.pdf?

Once that's done I'll be able to add the data for you 😄

**Comment by ChristlSnyman** [comment]
Hi Boyd

Thank you so much for reverting back.

Yes this is correct and would be great if you could add this 😀

Kind regards
Christl Snyman

**Comment by beyarkay** [comment]
Hey, no worries! busy working on it now actually. 

Could you confirm that the loadshedding is from 02h00 to 04h00, 04h00 to 06h00, etc (and not 02h00 to **04h30**, 04h00 to **06h30**, etc like the other eskom shed areas?

**Comment by ChristlSnyman** [comment]
Hi

So it's usually scheduled for 3 hours art a time but usually only off for 2
hours. This evening was scheduled 18:00 - 21:00 but came back on at 20:00.
See attached screen shot from EskomSePush app.

Hope this helps.

**Comment by beyarkay** [comment]
Okay, so is the PDF on the website incorrect then? It only says you have loadshedding for 2 hours at a time: https://www.ekurhuleni.gov.za/for-me/load-shedding-schedules/ 

Taking a skim through EskomSePush, it looks like the schedule is the same as what is in the PDF, just with an extra hour added onto the end.

Once you confirm this then Ekurhuleni will be done! I'll send the links here when the calendars are publicly available

**Comment by ChristlSnyman** [comment]
It is only for two hours although the app says 3 but it never is 3 hours. I
think the schedule is more accurate than the app.

**Comment by beyarkay** [comment]
Okay cool. I've declared you the sole representative of Ekurhuleni 😉 2 hours it is.

**Comment by beyarkay** [comment]
And it's done! You can get the calendars by going to [the releases page](https://github.com/beyarkay/eskom-calendar/releases/tag/latest), but I've pasted them here for your convenience. You'll want to right-click, copy the link, and then look in your calendar app for an option like `subscribe to internet calendar`, then paste the link there. After that, it will just work!

By the way, how did you find out about the project?


- [gauteng-ekurhuleni-block-1](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-1.ics)
- [gauteng-ekurhuleni-block-2](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-2.ics)
- [gauteng-ekurhuleni-block-3](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-3.ics)
- [gauteng-ekurhuleni-block-4](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-4.ics)
- [gauteng-ekurhuleni-block-5](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-5.ics)
- [gauteng-ekurhuleni-block-6](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-6.ics)
- [gauteng-ekurhuleni-block-7](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-7.ics)
- [gauteng-ekurhuleni-block-8](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-8.ics)
- [gauteng-ekurhuleni-block-9](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-9.ics)
- [gauteng-ekurhuleni-block-10](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-10.ics)
- [gauteng-ekurhuleni-block-11](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-11.ics)
- [gauteng-ekurhuleni-block-12](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-12.ics)
- [gauteng-ekurhuleni-block-13](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-13.ics)
- [gauteng-ekurhuleni-block-14](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-14.ics)
- [gauteng-ekurhuleni-block-15](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-15.ics)
- [gauteng-ekurhuleni-block-16](https://github.com/beyarkay/eskom-calendar/releases/download/latest/gauteng-ekurhuleni-block-16.ics)

**Comment by ChristlSnyman** [comment]
Fantastic thank you.

What does sole representative mean lol

I'm just a frustrated resident hahaha

**Comment by beyarkay** [comment]
Nah I'm just making a joke about how you get to decide if loadshedding is 2 hours or 3 hours. Glad I could help. How did you find out about the project?

**Comment by ChristlSnyman** [comment]
Awesome thank you so much. I will share with all my friends and family too.

I heard about you on Anele's show through The Good Guy who mentioned your
story and where to find the link.

Amazing work keep it up!
