### ISSUE TITLE
Westonaria Munic 3B

### ISSUE THREAD

**Issue by reapereast** [beyarkay/eskom-calendar#413]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

**Comment by reapereast** [comment]
![image](https://github.com/beyarkay/eskom-calendar/assets/134326556/6021c5bb-7a7b-4f9e-bf5f-861977a3ddcf)


This should be the right one for Westonaria

**Comment by beyarkay** [comment]
Original title: Missing area schedule for Westonaria Munic 3B the schedules for the current 3 westonaria zones is not right the one that is one the app loadshedding notifier say the location is Westonaria Munic -3B and it is correct


Busy looking into it now...

**Comment by reapereast** [comment]
it is

   - Westonaria Municipality - 3B

**Comment by reapereast** [comment]
My Boss had a friend Working for Eskom 2 years ago and they send it through to us, all I know is that the attached screenshot above is the one for Westonaria.

**Comment by reapereast** [comment]
u can try and use this https://www.eskom.co.za/distribution/customer-service/outages/municipal-loadshedding-schedules/
to check your book and area 




then use this link to check the schedule  https://www.tshwane.gov.za/wp-admin/admin-ajax.php?juwpfisadmin=false&action=wpfd&task=file.download&wpfd_category_id=293&wpfd_file_id=38390


Maybe this help a bit that is the tool they used to check our loadshedding schedule

**Comment by beyarkay** [comment]
Okay thanks, I'll check it out in the morning and see what I can do.

**Comment by reapereast** [comment]
Any Luck on loading that sheet to the Schedule?

**Comment by reapereast** [comment]
Hi so when will you be able to add the above-mentioned schedule it is the right one and it will help a lot the screenshot above is 100% accurate for our zone

**Comment by reapereast** [comment]
Hi Any luck yet loading the above sheet to the calendar, with the high load on the grid, it is hard to keep everyone up to date.

**Comment by reapereast** [comment]
Schedule changed after it went to city power and you never responded
