### ISSUE TITLE
berea

### ISSUE THREAD

**Issue by Kg0m0ts0** [beyarkay/eskom-calendar#437]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

**Comment by beyarkay** [comment]
Try searching for `berea` at https://eskomcalendar.co.za

<img width="969" alt="Screenshot 2023-06-06 at 14 37 51" src="https://github.com/beyarkay/eskom-calendar/assets/33420535/39cc6c99-80e5-409d-9819-275a0bf499ee">
