### ISSUE TITLE
Nelson Mandela Bay Schedules

### ISSUE THREAD

**Issue by IamC8** [beyarkay/eskom-calendar#447]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
None of the places in Mandela Bay

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Twitter

**Any other information**
https://www.nelsonmandelabay.gov.za/page/loadshedding

**Comment by beyarkay** [comment]
Thanks fro raising this, NMB might take a while (see [these other related issues](https://github.com/beyarkay/eskom-calendar/issues?q=is%3Aopen+label%3AD-nelson-mandela-bay+sort%3Aupdated-desc)) because the format is quite different to the rest of ZA

**Comment by IamC8** [comment]
I did do PR for the code to compile the times for NMB

**Comment by IamC8** [comment]
New code to generate all 38 groups in NMB
[IamC8-patch-11](https://github.com/IamC8/eskom-calendar/pull/12#issue-1779754811)

**Comment by beyarkay** [comment]
Fixed by 1074197. You can (finally) search for them in the website (: Let me know if you see any issues (but they should all be correct)
