### ISSUE TITLE
Not enough data from api

### ISSUE THREAD

**Issue by Rahaman2** [beyarkay/eskom-calendar#452]
When making a  get request to https://eskom-calendar-api.shuttleapp.rs/outages/{area_name} . The json response also include data from older dates but also sometimes fails to get the schedule for forthcoming dates. This makes the data hard to work with

**please fix this issue**

**Comment by beyarkay** [comment]
Hi there, can you give an example of what you expected to get and the what you actually got? Also please include the area_name that you were having trouble with
