### ISSUE TITLE
Missing area schedule

### ISSUE THREAD

**Issue by MikeKnightGit** [beyarkay/eskom-calendar#459]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

Verwoerd Park (12)
City of johannesburg 

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!
I bought a Solar Assistant and I'm trying to use the BETA version to integrate the load shedding schedule. 

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

**Comment by beyarkay** [comment]
I can't find Verwoerd Park (12) CoJ on eskom se push.

Verwoerd Park (12) City of **Ekurhuleni**?

If you do mean *ekurhuleni*, I've pushed an update which should fix this (it'll be live in ~5minutes).

Let me know if you've got any other troubles!

**Comment by MikeKnightGit** [comment]
Thanks so much, It is Ekurhuleni, Not sure why i typed Johannesburg. Thanks so much.

**Comment by MikeKnightGit** [comment]
Was able to find area on the site, Thanks again.

**Comment by beyarkay** [comment]
Great! If you like the project, leaving a "star" (on [the main github page](https://github.com/beyarkay/eskom-calendar)) is a great way to support it. That and telling your friends about it (:
