### ISSUE TITLE
Add schedule for Ethekwini

### ISSUE THREAD

**Issue by beyarkay** [beyarkay/eskom-calendar#46]
Request from: https://twitter.com/byronpbrummer/status/1570286440323366913?s=20&t=cPkCtM4dQ08G0M1WQDnaag

Source URL: https://www.durban.gov.za/pages/residents/load-shedding

**Comment by mich-a-b** [comment]
Congrats for being on the radio.

Could you also have a look at adding Stellenbosch/Cloetesville ?

**Comment by beyarkay** [comment]
@mich-a-b see issue https://github.com/beyarkay/eskom-calendar/issues/47

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:

- Ethekwini A: https://eskomcalendar.co.za/ec?calendar=eskom-direct-12-even.ics
- Ethekwini B: https://eskomcalendar.co.za/ec?calendar=eskom-direct-15-even.ics

You can also search for other areas by going to https://eskomcalendar.co.za/ and typing your area in the search box.

Hope that helps! feel free to reopen the issue if you've got other questions.
