### ISSUE TITLE
Eskom schedule for block 9 jhb incorrect 

### ISSUE THREAD

**Issue by Sly-west** [beyarkay/eskom-calendar#463]
Hi there, 

Not picking up the 6pm load shedding for today for my area.

Block 9 Mid Ennerdale

It was correct up until the early morning outage.

**Comment by beyarkay** [comment]
Hey there, 

Thanks for letting me know. There actually isn't any confirmed loadshedding from 16h onwards today, ESP is just assuming that there'll be loadshedding. [Here's Eskom's tweet](https://twitter.com/Eskom_SA/status/1690350424413368320) announcing a loadshedding schedule up until 16h today:

![Screenshot 2023-08-14 at 12 08 30](https://github.com/beyarkay/eskom-calendar/assets/33420535/3404a807-464a-4593-83a4-50ea35980927)

And here's a screenshot of the ESP app confirming that they don't actually know what's happening after 16h:

![photo_2023-08-14 12 07 06](https://github.com/beyarkay/eskom-calendar/assets/33420535/4c0219b3-5cfb-499f-a415-cefb8fccc133)

When Eskom announces an update, I'll update the calendars and you'll be all set.

**Comment by Sly-west** [comment]
Hi,

Thank you for your response, much appreciated.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Sly-west** [comment]
Hi,

I just saw this, I think stage 3 will kick in from 4pm today, this means my area should be affected 4-6:30pm


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by beyarkay** [comment]
Closing as the schedules are the same as ESP: 18h to 20h30 https://eskomcalendar.co.za/ec?calendar=city-power-9.ics

**Comment by Sly-west** [comment]
Hi,

How are you?

Please help I need the new calandar file for loashedding for block 15 for my gmail account.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
