### ISSUE TITLE
Add Loadshedding for Stellenbosch Farms: Cloetesville/Raithby/etc

### ISSUE THREAD

**Issue by beyarkay** [beyarkay/eskom-calendar#47]
[mich-a-b](https://github.com/beyarkay/eskom-calendar/issues/46#issuecomment-1248555003)

> Congrats for being on the radio.
> Could you also have a look at adding Stellenbosch/Cloetesville ?

Currently struggling to find a source of information about the loadshedding schedule in Cloetesville. There's [this page](https://stellenbosch.gov.za/eskom-schedule/), although I'm not sure when Stellenbosch central is shed by stellenbosch and when it's shed by Eskom

@mich-a-b could you confirm that you use the timetable in the link?

Alternatively, EskomSePush reference this link as their source of information for Cloetesville, although it doesn't seem to load:

http://stellenbosch.gov.za/news/notices/notices-engineering/6330-loadshedding-stage-1-4-schedule-2018/file

**Comment by mich-a-b** [comment]
Hi @beyarkay.

So your schedule for Stellenbosch Central is correct, it's because Cloetesville falls under Stellenbosch Farms (Zone 8).

I did find the following site where I could search for Cloetesville: https://loadshedding.eskom.co.za/

When I inspected the website I see it just pulls on the following endpoint:

https://loadshedding.eskom.co.za/LoadShedding/GetScheduleM/1061674/4/Western%20Cape/700

**Comment by beyarkay** [comment]
Ah okay, cheers. I'll get it added in the next few days, I'm just pretty busy this weekend so won't be able to get to it before Monday I'm afraid

**Comment by mich-a-b** [comment]
No problem at all, just glad I can help! Can't wait to uninstall ESP.

**Comment by beyarkay** [comment]
@ChristoViljoen [left a comment](https://github.com/beyarkay/eskom-calendar/issues/74#issue-1382945393) also needing the stellenbosch farms area:

> Would you be able to add the Raithby schedule as well. It falls under Stellenbosch.
> 
> EskomSePush has it as Raithby(8) with description Eskom Direct, Stellenbosch, Western Cape. Raithby doesn't fall under Stellenbosch's main schedule. It seems to fall under the Stellenbosch Farmers block 8 which includes:
> 
> Block 8: Cloetesville, De Zalze, Franschhoek, Jamestown, Raithby, Koelenhof, Kylemore, Kayamandi, Vlottenburg, Plankenburg, La Motte, Lanquedoc (Dwarsrivier), Lynedoch and Pniel

In terms of finding schedules, I can find [this page](https://stellenbosch.gov.za/eskom-schedule/) from stellenbosch.gov.za which contains schedules for three blocks:

- Block 2: Stellenbosch Central, University of Stellenbosch, Ida’s Valley, Die Boord, Paradyskloof, CBD and surrounding areas
- Block 8: Cloetesville, De Zalze, Franschhoek, Jamestown, Raithby, Koelenhof, Kylemore, Kayamandi, Vlottenburg, Plankenburg, La Motte, Lanquedoc (Dwarsrivier), Lynedoch and Pniel
- Block 16: Klapmuts, Bloekombos, Muldersvlei 

**But** it only has schedules up to stage 4, which isn't too useful. Alternatively, downloading [the western cape xlsx](https://www.eskom.co.za/distribution/wp-content/uploads/2022/09/WesternCape_LS.xlsx) file from [this eskom.co.za website](https://www.eskom.co.za/distribution/customer-service/outages/downloadable-loadshedding-spreadsheets-for-eskom-customers/) does give schedules for all of block 8.

The best way forward might be to create another scraper to download the xlsx files and parse them, although I'm not sure how easy it will be to handle xlsx. I see pandas has a `pd.from_xlsx` method though.

**Comment by beyarkay** [comment]
Hi!

This issue should be resolved, due to the creation of the project's website: https://eskomcalendar.co.za

You can either follow the link and search for an area, or you can use one of the links below:

- Idas Valley: https://eskomcalendar.co.za/ec?calendar=eskom-direct-8-odd.ics
- Cloetesville: https://eskomcalendar.co.za/ec?calendar=eskom-direct-8-odd.ics
- Franschoek: https://eskomcalendar.co.za/ec?calendar=western-cape-franschoek.ics
- Klapmuts: https://eskomcalendar.co.za/ec?calendar=eskom-direct-16-odd.ics
- Bloekombos: https://eskomcalendar.co.za/ec?calendar=eskom-direct-4-odd.ics
- Lynedoch: https://eskomcalendar.co.za/ec?calendar=eskom-direct-8-odd.ics
- Pniel: https://eskomcalendar.co.za/ec?calendar=eskom-direct-16-odd.ics


Although there are still areas like de zalze which aren't listed.

**Comment by beyarkay** [comment]
This is fully fixed by 33290e3, and all areas mentioned above can now be searched for on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)

**Comment by beyarkay** [comment]
As a final note, (and if you like the project), leaving a "star" (there's a button on [the main page](https://github.com/beyarkay/eskom-calendar)) would be much appreciated, as this helps more people discover eskom-calendar
