### ISSUE TITLE
Missing area schedule: Lorraine, Port Elizabeth (NMB)

### ISSUE THREAD

**Issue by jahnroux** [beyarkay/eskom-calendar#472]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Lorraine, a suburb in Port Elizabeth. Lorraine however is a large area so has a number of schedules within in. My area specifically is named the following in ESP: Lorraine (Area24) (12) | Nelson Mandela Bay Municipality

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
SolarAssistant

**Comment by beyarkay** [comment]
Hey, thanks for raising the issue. Nelson Mandela Bay has a weirdly formatted schedule so we haven't added it yet, but plans are underway to do so. I'll update this issue when we've added NMB to eskom-calendar.
