### ISSUE TITLE
Missing area schedule

### ISSUE THREAD

**Issue by Moon-developer** [beyarkay/eskom-calendar#475]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Buccleuch Outlying (16)

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
A search on github for "loadshedding"

**Comment by beyarkay** [comment]
Thanks for raising the issue, I'll get to this as soon as I can. Just a bit busy with personal work at the moment.

**Comment by beyarkay** [comment]
Actually, this was a much easier fix than I first thought.

As of 22989e8e353f82f8dfb4bea3e256024fac7ce50c, you can now search for "buccleuch outlying" and see your calendar in eskom-calendar. It's ID is `eskom-direct-16-even` and you can see it at this link: https://eskomcalendar.co.za/ec?calendar=eskom-direct-16-even.ics

![Screenshot 2023-09-14 at 15 52 11](https://github.com/beyarkay/eskom-calendar/assets/33420535/926c8830-1ae2-47b3-a50b-f571c41433eb)

Let me know if you've got any other questions, and star the repo if you like the project (:
