### ISSUE TITLE
no data since yesterday 24.09.23 ""message":"project not ready..."

### ISSUE THREAD

**Issue by Ohwelt** [beyarkay/eskom-calendar#483]
Since yesterday - the GET http request (and other regions as well) poll:
https://eskom-calendar-api.shuttleapp.rs/outages/eskom-direct-13-odd

results in this error message:
{"message":"project not ready. Try running `cargo shuttle project restart`.","status_code":503}

Thanks

**Comment by beyarkay** [comment]
Hey, this should be fixed now. Not entirely sure what happened here, I think it's something to do with my API provider. Will get some details.

**Comment by Ohwelt** [comment]
Great!
Working again.
Thanks Boyd for the quick fix!

**Comment by beyarkay** [comment]
No worries 😄 If you like the project, leaving a star or sharing with a friend is always appreciated. Let me know if anything else happens!

**Comment by Ohwelt** [comment]
Hi Boyd,
Unfortunately same issue again:

{"message":"project not ready. Try running `cargo shuttle project restart`.","status_code":503}

or even sometimes:
HTTP ERROR 500

**Comment by beyarkay** [comment]
Thanks for letting me know. As mentioned in #484 , there's been some trouble with the service that hosts the API.
