### ISSUE TITLE
{"message":"project not ready. Try running cargo shuttle project restart.","status_code":503}

### ISSUE THREAD

**Issue by Ohwelt** [beyarkay/eskom-calendar#484]
Hi Boyd,
Unfortunately same issue again:

{"message":"project not ready. Try running cargo shuttle project restart.","status_code":503}

or even sometimes:
HTTP ERROR 500

**Comment by Ohwelt** [comment]
just up again now (12:40)

**Comment by beyarkay** [comment]
Hey, thanks for letting me know, I really appreciate it. The service I use to host the API is having some trouble at the moment, we're trying to figure something out so there aren't any outages.
