### ISSUE TITLE
Missing: Humewood (NMB)

### ISSUE THREAD

**Issue by wikkel15** [beyarkay/eskom-calendar#487]
** missing information for Port Elizabeth (gqeberha). Specifically for Humewood (area 27)

**Where did you hear about [eskomcalendar.co.za] heard about you on solar assistant. 

**Any other information**
Thanks for the help!!

**Comment by beyarkay** [comment]
Hey, thanks for raising the issue. NMB has been on the list for a while and hopefully I'll get to it this week (it takes a bit more effort than other areas)

**Comment by beyarkay** [comment]
This has been fixed by 1074197, see https://eskomcalendar.co.za/ec/?calendar=nelson-mandela-bay-group-14.ics. You can (finally) search for them in the website (: Let me know if you see any issues (but they should all be correct)
