### ISSUE TITLE
GitHub Actions needs to be run

### ISSUE THREAD

**Issue by aidanhorn** [beyarkay/eskom-calendar#497]
In city-of-cape-town-area-5, the .ics calendar shows that there will be loadshedding today (Friday 2023-12-01) from 16:00 to 18:30, with a so-called **stage 5**.

It is **not** stage 5 at that time, and the [YAML file has stage **2**](https://github.com/beyarkay/eskom-calendar/commit/d9cb0d6fe94eb0602bbe756658348c69c76e75d6#diff-3c88e6cdd3d5f1351e840ab5c315389bb0bdca9bc9efc6d23048db7770f76297R86). This event should only occur for stages 3 and up.

The calendar event states that the calendar was compiled on Wednesday 29 Nov 2023 at 05:51:27 (UTC+02:00) by run https://github.com/beyarkay/eskom-calendar/actions/runs/7028572121 , which seems far too old (given the recent changes). I suspect that GitHub Actions needs to be run.

I raised this matter in [this comment](https://github.com/beyarkay/eskom-calendar/commit/abbc619245b58b38a1803f97939a93256e0834d8#r133885875) yesterday.

**Comment by 4everoptimistic** [comment]
Same here. My area is no longer updated.
