### ISSUE TITLE
Missing: Sherwood Area 12 (8) (NMB)

### ISSUE THREAD

**Issue by dawiemaartens** [beyarkay/eskom-calendar#498]
**What area(s) couldn't you find on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
Please also give the province/municipality, our beautiful country has a surprising number of places that are named the same as each other. If you know what your area is named on EskomSePush, including that also helps a lot.

Sherwood Area 12 (8)

**Where did you hear about [eskomcalendar.co.za](https://eskomcalendar.co.za/ec)?**
This really helps us figure out what's working!

SolarAssistant

**Any other information**
If you've got any other info you think might be helpful, feel free to leave it here

**Comment by beyarkay** [comment]
Hey, thanks for raising the issue. NMB has been on the list for a while, I'm hoping to (finally) get to it this week. It's got some aspects which make it particularly irritating to work with.

**Comment by dawiemaartens** [comment]
Awesome thanks so much...

**Comment by beyarkay** [comment]
This has been fixed by 1074197, see https://eskomcalendar.co.za/ec/?calendar=nelson-mandela-bay-group-8.ics. You can (finally) search for them in the website (: Let me know if you see any issues (but they should all be correct)
