### ISSUE TITLE
HTTP ERROR 500 - eskom-calendar-api.shuttleapp.rs 

### ISSUE THREAD

**Issue by Ohwelt** [beyarkay/eskom-calendar#499]
The API request results in an HTTP ERROR 500
i.e. 
https://eskom-calendar-api.shuttleapp.rs/outages/eskom-direct-13-odd

**Comment by armand-horak** [comment]
Experiencing same issue

**Comment by beyarkay** [comment]
Hey, thanks for opening the issue, there was some trouble with the API provider, but it should all be fixed now. Please let me know if you have any more issues.

**Comment by Ohwelt** [comment]
Hi Boyd,

Unfortunately, I now receive:

"No areas found that match `eskom-direct-13-odd`“

Kind regards
Arne
