### ISSUE TITLE
No areas found that match `eskom-direct-13-odd`

### ISSUE THREAD

**Issue by Ohwelt** [beyarkay/eskom-calendar#507]
Hi Boyd,

Unfortunately this error message pops up again :-(
No areas found that match `eskom-direct-13-odd`
for:
https://eskom-calendar-api.shuttleapp.rs/outages/eskom-direct-13-odd

**Comment by Ohwelt** [comment]
Compared to last time, now 
https://eskomcalendar.co.za/ec?calendar=eskom-direct-13-odd.ics
also returns:
Could not find the loadshedding area named 'eskom-direct-13-odd.ics'

**Comment by beyarkay** [comment]
Hey, thanks for letting me know. #508 should have a temporary fix, the longer-term solution is to allow the specification of "stage 0" (no loadshedding) events so the program knows the difference between no loadshedding and no information

**Comment by Ohwelt** [comment]
:-(

"TimeoutError: Timeout awaiting 'request' for 120000ms : http://eskom-calendar-api.shuttleapp.rs/outages/eskom-direct-13-odd"

**Comment by Ohwelt** [comment]
also:
RequestError: connect ECONNREFUSED 18.132.234.15:80 : http://eskom-calendar-api.shuttleapp.rs/outages/eskom-direct-13-odd
