### ISSUE TITLE
City Power Update Needed

### ISSUE THREAD

**Issue by The8bitRebel** [beyarkay/eskom-calendar#509]
Hi There,

I’ve noticed that City Power seems to have updated the schedules across the board, and changed some areas too. Is there an ETA on when this update will reflect on Eskom Calendar?

I recall something happening similar to this in the past and OP mentioned changing of some CSV files. Not sure if the same is required now?

**Comment by beyarkay** [comment]
This should be fixed now, thanks to @declan-fitzpatrick via pull request https://github.com/beyarkay/eskom-calendar/pull/514
