### ISSUE TITLE
Block 9 Ennerdale calendar incorrect 

### ISSUE THREAD

**Issue by Sly-west** [beyarkay/eskom-calendar#510]
Good day

Thank you thank you for your service, please help, the calendar does not match the load shedding notifier with regards to Ennerdale Johannesburg.

For Friday 5 Jan 24

The outage time is 4pm but on the calendar it's 6pm and there is a 10pm slot as well which doesn't appear on the load shedding notifier app.

https://github.com/beyarkay/eskom-calendar/releases/download/latest/city-power-9.ics

Thank you much appreciated.
sm-mangale@outlook.com

**Comment by beyarkay** [comment]
This should be fixed now, thanks to @declan-fitzpatrick via pull request https://github.com/beyarkay/eskom-calendar/pull/514
