### ISSUE TITLE
Schedule not accurate

### ISSUE THREAD

**Issue by steviedeehook** [beyarkay/eskom-calendar#513]
JHB City Power 13 and 2 are no longer accurate, They are not coinciding with other sources or the loadshedding we're experiencing.
IE, in City Power 2 we had loadshedding from 12:00 till 14:00 today which was not on the calendar. The calendar has it from 22:00 till midnight.

**Comment by philmavedzenge** [comment]
experiencing the same issue for city power 2

**Comment by beyarkay** [comment]
This should be fixed now, thanks to @declan-fitzpatrick via pull request https://github.com/beyarkay/eskom-calendar/pull/514
