### ISSUE TITLE
API ERROR - CERT_HAS_EXPIRED

### ISSUE THREAD

**Issue by gsccb** [beyarkay/eskom-calendar#520]
Good Day
The API (https://eskom-calendar-api.shuttleapp.rs/schedules/mpumalanga-secunda) did work perfect, but now I getting a 'CERT_HAS_EXPIRED' error.
Any help or suggestions on this this error please?

Regards
Gert

**Comment by beyarkay** [comment]
Hi there, thanks for raising the issue. I'm not sure why this is happening, I've contacted the service I use to host the API, I'll let you know when I've got a fix. 

DO NOT try to ignore the certificate error just yet, not before I've confirmed that this is actually harmless and that there aren't any bad actors doing weird things.

**Comment by beyarkay** [comment]
The shuttle team is working on the problem. No ETA just yet.

**Comment by gsccb** [comment]
It seems the error has cleared, everything runs smooth again. Thank you so much and have a nice week.
Thank you for this helpful app.
Regards
Gert

**Comment by beyarkay** [comment]
As you spotted, the error has been fixed. Thanks for letting me know! I've you like the app, leaving a "star" on the main page is greatly appreciated (: https://github.com/beyarkay/eskom-calendar
