### ISSUE TITLE
Calendar events for Cape Town areas determined by national stages

### ISSUE THREAD

**Issue by francois-glucode** [beyarkay/eskom-calendar#68]
Great job on this project @beyarkay!

I noticed that my Cape Town area calendar events are updated as national stages change, whereas I'd expect the events to be updated if and when the Cape Town stages change

**Comment by beyarkay** [comment]
Hey again! Thanks for bringing it to my attention. The fix for this is a bit tricky to implement and has a large blast zone if it goes wrong/I make a mistake, so I've been thinking about how best to go about it. Rest assured a fix is coming though.

**Comment by beyarkay** [comment]
Closing this as its a duplicate of https://github.com/beyarkay/eskom-calendar/issues/62. @francois-glucode feel free to watch or comment on that issue if you want to be kept up-to-date with progress on that issue.
