### ISSUE TITLE
Python black formatting

### ISSUE THREAD

**Issue by beyarkay** [beyarkay/eskom-calendar#7]
Check the python script is properly formatted with [`black`](https://pypi.org/project/black/) and deny a push if it is not properly formatted.

**Comment by SpirosArk** [comment]
Hello which one is the script that should be checked?

**Comment by beyarkay** [comment]
Hey! All `*.py` scripts should be checked (There's only one at the moment, but may be more in the future). It's possible the script isn't already compliant with black, in which case you'll have to format it, commit and push the formatting, and then setup push-denial

**Comment by beyarkay** [comment]
Resolved by 34db59dfb80c0533d1e6a1b5992f644239ac6bab and with [this workflow](https://github.com/beyarkay/eskom-calendar/actions/workflows/python-check-formatting.yml)
