### ISSUE TITLE
Distinguished national vs local stages

### ISSUE THREAD

**Issue by emmanuelchemla** [beyarkay/eskom-calendar#75]
The stages vary from one area to another. For example:
- National is currently at Stage 5, 
- City of Cape Town is currently at Stage 3.

Can this be taken into account?

**Comment by beyarkay** [comment]
Hey! Thanks for the feedback, this issue is already tracked in https://github.com/beyarkay/eskom-calendar/issues/62 so I'm going to close this issue in favour of the existing one, but rest assured I'm working on the fix! you can watch #62 if you want to be notified on comments/progress.
