### ISSUE TITLE
Update stages automatically

### ISSUE THREAD

**Issue by emmanuelchemla** [beyarkay/eskom-calendar#76]
Are stages updated manually?

How about:
Scrape the info (shortly after) each new tweet from eskom, from pages like [this](https://www.capetown.gov.za/Family%20and%20home/Residential-utility-services/Residential-electricity-services/Load-shedding-and-outages
).

I would be more than happy to help with this (email me).

**Comment by beyarkay** [comment]
Hey! Thanks for the feedback. I've got an issue open for auto-scraping tweets open in #50 but I hadn't considered cape town as well. I'll continue the conversation there, so feel free to comment there and we can talk about options.
