### ISSUE TITLE
Schedule Missing for Eersterivier, Eastern Cape

### ISSUE THREAD

**Issue by paulbalinnel** [beyarkay/eskom-calendar#86]
hallo, pls will you add the schedule for Eersterivier in Eastern Cape? thanks!!!

**Comment by beyarkay** [comment]
Hey, thanks for the feedback! This is related to some other missing areas (they're all missing for the same reason, see this [tag](https://github.com/beyarkay/eskom-calendar/issues?q=is%3Aissue+is%3Aopen+label%3Amissing-area-schedule)) so I'll get on this ASAP.

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:
-  Eersterivier: https://eskomcalendar.co.za/ec?calendar=eskom-direct-16-even.ics
- Eersterivier Suid 1 & Suid 2: https://eskomcalendar.co.za/ec?calendar=eskom-direct-2-odd.ics

You can also search for other areas by going to https://eskomcalendar.co.za/ and typing your area in the search box.

Hope that helps! feel free to reopen the issue if you've got other questions.
