### ISSUE TITLE
Add regression tests on build artifacts

### ISSUE THREAD

**Issue by Andridb** [beyarkay/eskom-calendar#88]
Loadshedding scheduled for 14:00 to 16:30 today 25 September for Stage 3 but your calendar doesnt show it.

**Comment by beyarkay** [comment]
Hmm okay this is worrying. I'm going to use this as a prompt to set up better testing so that regressions like this don't happen (or at least, if they do happen then I get notified about it automatically). Should be able to get it fixed in the next few days.

**Comment by beyarkay** [comment]
Looking into solutions: https://stackoverflow.com/questions/73866402/compare-build-artifacts-from-two-different-commits-via-github-actions

**Comment by beyarkay** [comment]
Closing, as this is out of scope for the project
