### ISSUE TITLE
Support for some less obvious areas

### ISSUE THREAD

**Issue by beyarkay** [beyarkay/eskom-calendar#9]
Many areas are not shed by eskom and so don't have areas specified by eskom. Currently these areas just result in a log line like [`Cannot parse: Some("https://www.capetown.gov.za/Family%20and%20home/Residential-utility-services/Residential-electricity-services/Load-shedding-and-outages") "City of Cape Town"`](https://github.com/beyarkay/eskom-calendar/runs/7370251286?check_suite_focus=true#step:7:12) and there are no CSV files defining the national LS schedule for these areas.

A scraper should be created to download data and format them as CSVs in the same format as the existing CSVs

Additionally, these areas often have a different schedule than the rest of the country. Changes should be made to `src/main.rs` to enable `manually_specified.yaml` to accept a parameter like "shedder" or similar, so the schedules for the country and for the regionally-shed areas can be kept separate

Information sources for non-eskom shed areas:
- Lexity (for 2nd hand information in HTML tables) https://www.lexity.co.za/
- Emfuleni: https://www.eskom.co.za/distribution/wp-content/uploads/2021/06/emfuleni-load-shedding-schedule.pdf
- Tshwane: https://www.tshwane.gov.za/sites/Departments/Public-works-and-infrastructure/Pages/Load-Shedding.aspx
- ~citypower: https://www.citypower.co.za/customers/Pages/Load_Shedding_Downloads.aspx~ added in https://github.com/beyarkay/eskom-calendar/commit/d766ab4f17ba93472b4882f1d83058124471a14b
- ~Ekurhuleni: https://www.ekurhuleni.gov.za/for-me/load-shedding-schedules/~ Added in [9aafeef](https://github.com/beyarkay/eskom-calendar/commit/9aafeef4b4c052e879b8eb4be8e29adcc39a2bed)

Possible complications: 
- Stellenbosch shedding schedule might be more complicated than originally thought: https://stellenbosch.gov.za/eskom-schedule/

Interested parties: 
- Tswane: 
  - https://www.reddit.com/r/southafrica/comments/w3hq7v/get_loadshedding_schedules_in_your_calendar/igw933g/

**Comment by beyarkay** [comment]
Lexity: https://www.lexity.co.za/?provider=cpt might be a good data source for this.

**Comment by beyarkay** [comment]
Demand for Tswane and city power: https://www.reddit.com/r/southafrica/comments/w3hq7v/get_loadshedding_schedules_in_your_calendar/igw933g/

**Comment by beyarkay** [comment]
Also Stellenbosch shedding schedule might be more complicated than originally thought: https://stellenbosch.gov.za/eskom-schedule/

**Comment by beyarkay** [comment]
Gauteng/Citypower should be fixed by https://github.com/beyarkay/eskom-calendar/commit/d766ab4f17ba93472b4882f1d83058124471a14b. Calendars are building now. 

Also @GoodThingsGuy on twitter (20k followers) wants to know when Gauteng is confirmed https://twitter.com/GoodThingsGuy/status/1550057759516803072?s=20&t=xW7AtWRxtRJrbKN9ckRlhQ

**Comment by zeorin** [comment]
City Power *.ics files were part of a previous release, but I see that they are now gone…

**Comment by zeorin** [comment]
They are now back!

**Comment by beyarkay** [comment]
Not entirely sure what happened there though, they shouldn't have been gone in the first place. I just had to recompile the calendars in order to get them to appear again.

Opening this in a new issue so I can try root cause the problem.

**Comment by DyllanDarcy** [comment]
Hey mate,
This is an awesome project.
I'm not sure which ics file would be used for KwaZulu Natal, eThekwini Municipality, Waterfall, Block 8

Thanks in advance!
