### ISSUE TITLE
Val-die-vie and Pearl Valley missing

### ISSUE THREAD

**Issue by fransjrossouw** [beyarkay/eskom-calendar#90]
Paarl missing
Pearl Valley and Val de Vie missing

**Comment by beyarkay** [comment]
Hey! Thanks for letting me know. This is related to a few other missing areas, so I'll fix this ASAP.

**Comment by fransjrossouw** [comment]
Tx, Boyd.  Looking forward to trying it.

Frans Rossouw
082 883 5008
***@***.*** ***@***.***>

**Comment by Gideon-ZA** [comment]
Hi,

I have noticed Paarl has the same load shedding schedule as City Power -9.
I have been using it the past couple of weeks and the schedule is spot on.

**Comment by beyarkay** [comment]
Hi!

Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:
-  Paarl: https://eskomcalendar.co.za/ec?calendar=eskom-direct-14-odd.ics

You can also search for other areas by going to https://eskomcalendar.co.za/ and typing your area in the search box.

@fransjrossouw for Val-die-vie and Pearl Valley, I can't find that area on eskom's schedules nor on EskomSePush, does they have another name?

**Comment by fransjrossouw** [comment]
Hi BoydThanks for adding Paarl. The three Paarl (Drakenstein Municipality) areas are described here:http://www.drakenstein.gov.za/cc/Pages/Key-to-Eskom-load-shedding.aspxFrans Rossouwm +27 82 883 5008e   ***@***.*** is no present like the time.On 26 Jan 2023, at 12:40, Boyd Kane ***@***.***> wrote:﻿
Hi!
Sorry for the delay, adding these areas was a lot more complicated than anticipated. Here are your calendars:

Paarl: https://eskomcalendar.co.za/ec?calendar=eskom-direct-14-odd.ics

You can also search for other areas by going to https://eskomcalendar.co.za/ and typing your area in the search box.
@fransjrossouw for Val-die-vie and Pearl Valley, I can't find that area on eskom's schedules nor on EskomSePush, does they have another name?

**Comment by Gideon-ZA** [comment]
Hi,

I've looked at the schedule and it is unfortunately wrong for the Paarl area.
I've searched https://eskomcalendar.co.za/ and I cant find the correct one.

**Comment by beyarkay** [comment]
Hrmm okay thanks for letting me know, I'll look into it.

**Comment by beyarkay** [comment]
Hi @Gideon-ZA , I think I've fixed [Paarl](https://eskomcalendar.co.za/ec?calendar=eskom-direct-9-even.ics), I've checked and if search for "paarl" at https://eskomcalendar.co.za and then choose the Drakenstein option, the everything should be good.

**Comment by beyarkay** [comment]
Hi @fransjrossouw , I've mistakenly added `val-die-vie` as `val-de-vie` (I've got a fix on the way), so if you search for `val de vie` on [eskomcalendar.co.za](https://eskomcalendar.co.za/ec) then you'll find the correct schedule. Alternatively you can click [this link](https://eskomcalendar.co.za/ec?calendar=eskom-direct-8-even.ics).

**Comment by Gideon-ZA** [comment]
@beyarkay Thank you very much

**Comment by fransjrossouw** [comment]
Thank you - mauch appreciated.

Frans Rossouw
082 883 5008
***@***.*** ***@***.***>

**Comment by beyarkay** [comment]
No worries! I'm glad to help. 

As a final note (if you feel like the project is helpful) leaving a "star" (there's a button on [the main page](https://github.com/beyarkay/eskom-calendar)) would be much appreciated, as it helps more people discover eskom-calendar.
